SalesTradeShow/Controllers/SecurityController.cs
using System;
using System.Web;
using System.Web.Mvc;
using hme.Models;
using System.Web.Security;

using hmeUtil;
using HME.SQLSERVER.DAL;

namespace hme
{
    public class SecurityController : Controller
    {
        //
        // GET: /Security/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = new User() { Username = model.Username, Password = model.Password };
            ldap ldap = new ldap();

            user = ldap.GetUserDetails(user);
            Session["user"] = user;

            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(model.Username, false);

                var authTicket = new FormsAuthenticationTicket(1, user.Email, DateTime.Now, DateTime.Now.AddHours(12), false, user.Roles);
                string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                HttpContext.Response.Cookies.Add(authCookie);
                return RedirectToAction("Index", "Home");
            }

            else
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                return View(model);
            }
        }


        //
        // POST: /Security/LogOff
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            //AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            try
            {
                FormsAuthentication.SignOut();
            }
            catch { }
            return RedirectToAction("Index", "Home");
        }

        private string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;

            using (var stringWriter = new System.IO.StringWriter())
            {
                //var ctrl = new Controllers.HomeController();
                //ctrl.ControllerContext = ControllerContext;
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, stringWriter);
                viewResult.View.Render(viewContext, stringWriter);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);

                return stringWriter.GetStringBuilder().ToString();
            }
        }
    }
}

SalesTradeShow/Views/Security/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SalesTradeShow/Views/Security/Login.cshtml
@using hme.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container container-table">
    <div id="Content" class="content-login">
        @using (Html.BeginForm("Login", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
            @Html.AntiForgeryToken()
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 col-centered container-login-small animated fadeInDown">
                <div class="col-lg-12 col-login-right">
                    <div class="form-group">
                        <div class="col-lg-4"></div>
                        <div class="col-lg-4">
                            <div class="login-logo">
                                <img src="/images/HME-Logo-large.png" alt="HME" width="95" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group" style="margin-top:0;margin-bottom:0;">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8 col-min-pad">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8 col-min-pad">
                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Username" })
                            @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8 col-min-pad">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8 col-min-pad">
                            <input type="submit" value="Login" class="btn btn-primary form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-8 login-copy">
                            &copy;2016 HM Electronics, Inc., all rights reserved.
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>